command_timeout = 700

[character]
success_symbol = "[âœ](green)"
error_symbol = "[âœ](red)"

[battery]
full_symbol = "" # the battery is full
charging_symbol = "" # the battery is charging
discharging_symbol = "" # the battery is discharging
unknown_symbol = "" # the battery state is unknown
empty_symbol = "" # the battery state is empty
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 30
style = "yellow"

[[battery.display]]
threshold = 80
style = "green"

[cmd_duration]
show_milliseconds = true

[git_metrics]
disabled = false

[memory_usage]
disabled = false
threshold = 80
symbol = "ğŸ’¾ "

[nodejs]
symbol = "â£ "
